/* Ek filmler: [ad, yıl, imdb, yönetmen, açıklama] */
window.EXTRA={
slasher:[
["Candyman",1992,7.0,"Bernard Rose","Chicago'da şehir efsaneleri üzerine tez yazan Helen, aynaya beş kere adını söyleyenin karşısına çıkan kancalı kolu olan hayaletin gerçek olduğunu fark eder. Irk, sınıf ve efsane üzerine düşündüren şık bir slasher."],
["Child's Play",1988,6.6,"Tom Holland","Ölmek üzere olan bir seri katil, ruhunu bir \"İyi Adamlar\" oyuncağına aktarır. Chucky, küçük Andy'nin en iyi arkadaşı gibi görünür ama arkadan iş çevirmektedir. Mizahı ve efektleriyle 80'lerin sevilen bir korku filmi."],
["Sleepaway Camp",1983,6.2,"Robert Hiltzik","Yaz kampında şaka ve kazalar sandığı olaylar giderek ölümcül hâle gelir. Bir katil, kamp çocuklarını tek tek avlar. Şaşırtıcı finaliyle bir 80'ler kült slasher'ı."],
["Final Destination",2000,6.7,"James Wong","Uçak kazasını önceden gören Alex ile birkaç arkadaşı uçaktan inip ölümden kurtulur. Ancak Ölüm, planını bozanları tek tek alacaktır. Ağır, ince hesaplanmış \"kaza\" sahneleriyle bir seriyi başlattı."],
["Terrifier",2016,5.6,"Damien Leone","Cadılar Bayramı gecesinde iki kadın, soğuk ve sessiz bir palyaço olan Art'la karşılaşır. Aşırı gore sahneleriyle ünlenen, bağımsız bir slasher filmi."],
["A Bay of Blood",1971,6.4,"Mario Bava","Bir koyun mirası etrafında dönen cinayetler, bir bir akrabaları ve ziyaretçileri yok eder. Slasher türüne öncülük eden, Bava'nın İtalyan giallo geleneğinden kanlı bir yapımı."]],
hayalet:[
["The Changeling",1980,7.2,"Peter Medak","Karısını ve kızını kaybeden besteci John, Seattle'da büyük bir eve taşınır. Evde yıllardır kapalı kalmış bir oda ve çözülmeyi bekleyen bir cinayet vardır. Atmosferik ve ürkütücü bir hayalet filmi."],
["The Orphanage",2007,7.4,"J.A. Bayona","Çocukluğunu geçirdiği yetimhaneyi yeniden açan Laura'nın oğlu hayali bir arkadaşla konuşmaya başlar ve bir gün kaybolur. Anne, çocuğu bulmak için evin sırlarına dalar. Hem korkutan hem de ağlatan bir İspanyol klasiği."],
["Lights Out",2016,6.3,"David F. Sandberg","Işıklar kapandığında beliren bir varlık, Rebecca'nın ailesini yıllardır takip etmektedir. Işığı açık tutmak tek savunmadır. Kısa filminden uzatılmış, yaratıcı sıçrama korkularıyla dolu bir yapım."],
["Mama",2013,6.2,"Andy Muschietti","Beş yıl ormandaki kulübede yalnız yaşayan iki küçük kız bulunur ve amcalarının evine yerleştirilir. Ancak yanlarında görünmeyen bir \"Mama\" da gelmiştir. Del Toro'nun yapımcılığıyla çekilmiş bir gotik korku."],
["The Conjuring 2",2016,7.3,"James Wan","Warren çifti bu kez Londra'nın Enfield bölgesinde, bir ailenin başına musallat olan ruhu araştırır. Gerçek bir olaydan uyarlanan film, önceki bölümün gerilimini daha da yükseltir."],
["Don't Look Now",1973,7.1,"Nicolas Roeg","Venedik'te kızlarının ölümünden sonra yas tutan bir çift, görme engelli bir medyumla tanışır. Kadın, çocuğun ruhunun onlara mesaj verdiğini söyler. Kırmızı pelerinli bir figür ve unutulmaz bir finalle şiirsel bir hayalet filmi."],
["The Woman in Black",2012,6.4,"James Watkins","Genç avukat Arthur Kipps, ıssız bir malikânenin evraklarını düzenlemek için köye gider. Köylüler, siyah giysili hayaletin görünmesinin çocuk ölümlerine yol açtığına inanır. Daniel Radcliffe'in başrolde olduğu klasik tarzda bir hayalet hikâyesi."],
["The Autopsy of Jane Doe",2016,6.8,"André Øvredal","Bir otopsi uzmanı ve oğlu, bir cinayet mahallinde bulunan kimliği belirsiz kadının cesedini inceler. Gece boyunca ceset hakkında ürkütücü şeyler keşfederler. Tek mekânda geçen gerilimli bir film."]],
seytani:[
["The Exorcist III",1990,6.5,"William Peter Blatty","Yıllar önce ölen bir seri katilin cinayetleri yeniden başlar. Dedektif Kinderman, akıl hastanesinde şüpheli bir hasta ile karşılaşır. Atmosferik, tek bir sahneyle ünlü olan, kendi başına ürkütücü bir devam filmi."],
["Prince of Darkness",1987,6.7,"John Carpenter","Bir rahip ve bir grup bilim insanı, bir kilisenin bodrumunda duran gizemli yeşil sıvıyı araştırır. Sıvı, kötülüğün kendisini içermektedir. Carpenter'ın kasvetli ve sürekli artan gerilimli şeytani filmi."],
["Drag Me to Hell",2009,6.6,"Sam Raimi","Bankacı Christine, yaşlı bir kadının kredisini reddedince çingene laneti altına girer. Üç gün sonra bir iblis ruhunu cehenneme sürükleyecektir. Raimi'nin hem korkutan hem de güldüren hızlı temposu."],
["Veronica",2017,6.2,"Paco Plaza","Madrid'de bir kız, ruh çağırma seansı yaptıktan sonra bir varlıkla karşılaşır ve küçük kardeşlerine bakmak zorunda kalır. Gerçek bir polis dosyasından esinlenen film, ürkütücü atmosferiyle dikkat çeker."],
["Saint Maud",2019,6.6,"Rose Glass","Dindar hemşire Maud, ölümcül hasta bir dansçıya bakarken onun ruhunu kurtarma takıntısına kapılır. İnanç ve delilik arasındaki sınır bulanıklaşır. Rose Glass'ın etkileyici ilk filmi."],
["Angel Heart",1987,7.3,"Alan Parker","1955 New York'unda özel dedektif Harry Angel, kayıp bir şarkıcıyı ararken Louisiana'nın vudu dünyasına girer. Her adımda ölüm ve gizem büyür. Karanlık ve sarsıcı finaliyle bir neo-noir ve şeytani korku birleşimi."]],
zombi:[
["Zombi 2",1979,6.8,"Lucio Fulci","Bir kayıp tekne New York'a gelir ve içinden bir zombi çıkar. Bir kadın ve bir gazeteci, sorunun kaynağı olan Karayip adasına gider. Meşhur göz sahnesiyle bir İtalyan gore klasiği."],
["Dawn of the Dead",2004,7.3,"Zack Snyder","Aniden başlayan bir zombi salgınında hemşire Ana, birkaç hayatta kalanla bir alışveriş merkezine sığınır. Romero'nun klasiğinin hızlı zombilerle yeniden yorumu. Kıyamet atmosferi çok iyi kurulmuş."],
["The Girl with All the Gifts",2016,6.6,"Colm McCarthy","Enfeksiyonlu çocukların yetiştirildiği bir askeri tesiste zeki küçük Melanie, öğretmeniyle özel bir bağ kurar. Bir saldırı sonrası dışarıya çıkmaları gerekir. Zombi türüne duygusal bir bakış."],
["Dead Snow",2009,6.2,"Tommy Wirkola","Norveç dağlarında kulübe tatiline çıkan tıp öğrencileri, İkinci Dünya Savaşı'ndan kalma Nazi zombileriyle karşılaşır. Aşırı kanlı ve komik bir film."],
["#Alive",2020,6.2,"Cho Il-hyung","Zombi salgını başlarken bir genç, apartman dairesinde yalnız kalır. İnternet, yiyecek ve umut azalırken karşı dairede bir hayatta kalan daha olduğunu fark eder. Kapalı alanda geçen Güney Kore yapımı."],
["The Night Eats the World",2018,6.4,"Dominique Rocher","Zombi salgını sırasında Sam, bir Paris apartmanında uyuya kalır ve ertesi gün tek kalmış olarak uyanır. Yalnızlığa ve sessizliğe odaklanan, farklı bir zombi filmi."]],
vampir:[
["Horror of Dracula",1958,7.1,"Terence Fisher","Van Helsing, Kont Dracula'yı bulmak ve durdurmak için Transilvanya'ya gider. Renkli çekimleri ve Christopher Lee'nin Dracula'sıyla Hammer'ın ikonik gotik korku klasiği."],
["The Lost Boys",1987,7.2,"Joel Schumacher","Yeni bir sahil kasabasına taşınan iki kardeş, bölgenin genç vampir çetesiyle karşılaşır. 80'lerin müziği ve havasıyla vampir türünü gençlik filmine çeviren, sevilen bir film."],
["30 Days of Night",2007,6.6,"David Slade","Alaska'da bir kasaba, bir ay boyunca güneş doğmadan geçecektir. Vahşi vampirler bu karanlıktan faydalanır. Hayatta kalanlar, ışığa kadar dayanmak zorundadır."],
["Only Lovers Left Alive",2013,7.3,"Jim Jarmusch","Yüzyıllardır yaşayan iki vampir aşığı, Detroit'te ve Tanca'da modern dünyanın çöküşünü izler. Sakin, şiirsel ve şık bir vampir filmi."],
["Blade",1998,7.1,"Stephen Norrington","Yarı insan, yarı vampir Blade, vampir toplumunun gizli dünyasına karşı savaş açar. Aksiyon ve korkuyu harmanlayan, vampir çizgi roman uyarlamalarının öncüsü."],
["From Dusk Till Dawn",1996,7.3,"Robert Rodriguez","Kaçak iki kardeş, Meksika sınırında bir striptiz barına girince vampirlerin yuvasına düşer. Tarantino'nun senaryosuyla, film ortasında tür değiştiren eğlenceli bir film."],
["Ginger Snaps",2000,6.7,"John Fawcett","Kız kardeşler Ginger ve Brigitte, bir kurt adam ısırığı sonrası Ginger'ın değişmeye başladığını fark eder. Ergenlik ve dönüşümü kurt adam alegorisiyle işleyen kült bir film."],
["Dog Soldiers",2002,6.8,"Neil Marshall","İskoçya ormanlarında tatbikat yapan askerler, kurt adamlarla dolu bir bölgeye girer. Kırsal bir eve sığınır ve geceyi atlatmaya çalışır. Aksiyonu bol, eğlenceli bir kurt adam filmi."],
["A Girl Walks Home Alone at Night",2014,6.7,"Ana Lily Amirpour","İran kasabasında dolaşan yalnız bir kız, geceleri kötü adamları avlayan bir vampirdir. Siyah beyaz, şiirsel ve moda bir vampir western'i."]],
psikolojik:[
["Misery",1990,7.8,"Rob Reiner","Bir yazar, kar fırtınasında araba kazası geçirir ve en büyük hayranı Annie tarafından kurtarılır. Annie, onu kendi evinde tutar ve yeni romanını yazmaya zorlar. Kathy Bates'e Oscar kazandıran bir gerilim."],
["Carrie",1976,7.4,"Brian De Palma","Dindar annesi tarafından ezilen, sınıfta alay edilen Carrie'nin telekinetik güçleri vardır. Balo gecesi her şey tersine döner. Stephen King'in ilk uyarlamalarından biri."],
["Perfect Blue",1997,8.0,"Satoshi Kon","Pop şarkıcısı Mima, aktrisliğe geçtikten sonra takipçisi tarafından rahatsız edilir. Gerçek ile kurgu birbirine karışır. Hayranlık uyandıran bir animasyon psikolojik gerilimi."],
["Session 9",2001,6.5,"Brad Anderson","Terk edilmiş bir akıl hastanesinde asbest temizliği yapan ekip, eski hasta kayıtlarına rastlar. İşçilerin zihni giderek bozulur. Gerçek bir hastanede çekilmiş, soğuk bir gerilim."],
["The Lighthouse",2019,7.4,"Robert Eggers","1890'larda ıssız bir adada iki deniz feneri bekçisi, fırtınalar ve yalnızlık yüzünden birbirlerine ve kendilerine karşı delirir. Siyah beyaz çekilmiş, Willem Dafoe ve Robert Pattinson'ın muhteşem oyunculuğu."],
["Pearl",2022,6.8,"Ti West","1918'de Teksas çiftliğinde yaşayan Pearl, yıldız olma hayalleriyle yanar. Ailesinin baskısı ve hayal kırıklıkları onu karanlığa sürükler. Mia Goth'un unutulmaz performansıyla bir \"X\" ön hikâyesi."],
["The Tenant",1976,7.5,"Roman Polanski","Paris'te intihar eden bir kadının dairesine taşınan Trelkovsky, komşularının onu o kadın gibi davranmaya zorladığını düşünür. Paranoya ve kimlik kaybını işleyen, Polanski'nin kasvetli filmi."],
["Cure",1997,7.4,"Kiyoshi Kurosawa","Tokyo'da cesetlerin boğazında aynı X şeklinde kesikler bulunur, ama katiller birbirinden bağımsız insanlardır. Dedektif Takabe, hepsini bağlayan gizemli bir adamı bulur. Yavaş, sessiz ve çok rahatsız edici."]],
foundfootage:[
["Hell House LLC",2015,6.2,"Stephen Cognetti","Bir ekip, hayalet evi turu hazırlamak için terk edilmiş bir oteli dekore eder. Açılış gecesinde bir felaket yaşanır. Sonradan bulunan görüntüleri anlatan, ürkütücü bir found footage."],
["Creep",2014,6.2,"Patrick Brice","Bir video çekimcisi, kırsalda yaşayan hasta bir adamı çekmek için işe gider. Adamın tuhaflığı gittikçe artar. İki kişilik, gerilimi yavaş yükselen, mizahi ve rahatsız edici bir film."],
["Noroi: The Curse",2005,7.0,"Kôji Shiraishi","Doğaüstü olayları araştıran bir belgeselci, bir ailenin ve çevresindeki tuhaf olayların izini sürer. Sahte belgesel formatında çekilmiş, dikkatle örülmüş bir Japon korkusu."],
["The Last Exorcism",2010,6.3,"Daniel Stamm","Sahte şeytan çıkarıcılık yapan bir vaiz, bir belgesel ekibiyle Louisiana'da yaşayan bir kızın vakasına bakar. Ama bu sefer işler sandığından farklıdır."],
["Late Night with the Devil",2023,7.0,"Colin Cairnes, Cameron Cairnes","1977'de gece yarısı bir talk show, Cadılar Bayramı özel yayınında şeytani bir vakaya ev sahipliği yapar. Yayın canlı devam ederken olaylar kontrolden çıkar."],
["Gonjiam: Haunted Asylum",2018,6.0,"Jung Bum-shik","Bir internet kanalı ekibi, terk edilmiş bir hastaneyi canlı yayınlamak için gider. Gece ilerledikçe ürkütücü olaylar yaşanır. Güney Kore'den bir found footage."],
["Unfriended",2014,5.6,"Levan Gabriadze","Bir grup lise arkadaşı, bir bilgisayar ekranı üzerinden görüntülü sohbet ederken ölen arkadaşlarının hesabından mesaj alır. Tüm film bir ekran üzerinde geçer."],
["The Taking of Deborah Logan",2014,6.0,"Adam Robitel","Alzheimer hastası yaşlı bir kadının kızı, bir belgesel ekibine annesini çekmesine izin verir. Hastalıktan fazlası olduğu anlaşılınca olaylar sarpa sarar."]],
body:[
["Shivers",1975,6.4,"David Cronenberg","Bir bilim insanının geliştirdiği parazit, lüks bir apartman kompleksinde yaşayanları cinsel dürtülerle dolu yaratıklara dönüştürür. Cronenberg'in beden korkusunun ilk büyük örneği."],
["Rabid",1977,6.4,"David Cronenberg","Motosiklet kazası sonrası ameliyat edilen genç kadının koltuk altından, kan emen bir organ çıkar. Dayanılmaz açlık, Montreal'de bir salgına yol açar."],
["The Brood",1979,6.8,"David Cronenberg","Psikolog Dr. Raglan'ın yeni bir terapi yöntemi, hastasının öfkesini fiziksel yaratıklara dönüştürür. Boşanma ve çocuk istismarı temalı, karanlık ve rahatsız edici."],
["Dead Ringers",1988,7.2,"David Cronenberg","İkiz jinekologlar Beverly ve Elliot, bir hastayla ilişkileri yüzünden birbirlerine olan bağlılıklarını tehlikeye atar. Jeremy Irons'ın ikili performansı."],
["Tetsuo: The Iron Man",1989,7.0,"Shinya Tsukamoto","Bir adam, bir kazadan sonra vücudunun metal parçalara dönüşmeye başladığını görür. Siyah beyaz, hızlı kurgulu ve yoğun bir Japon cyberpunk korku filmi."],
["Slither",2006,6.5,"James Gunn","Küçük bir kasabaya düşen göktaşından çıkan parazit, bir adamı ele geçirir ve insanları solucan benzeri varlıklara dönüştürür. Gore ve mizahı birleştiren eğlenceli bir film."],
["Splice",2009,5.7,"Vincenzo Natali","İki genetik bilimci, insan ve hayvan DNA'sını birleştirerek yeni bir canlı yaratır. Yaratık hızla büyüyüp değişirken etik sınırlar bulanıklaşır."]],
folk:[
["Hagazussa",2017,6.4,"Lukas Feigelfeld","15. yüzyıl Alp dağlarında yalnız yaşayan Albrun, köylülerin cadı dedikodularıyla dışlanır. Doğa ve izolasyon baskısı onu giderek içine kapanmış bir korkuya iter. Yavaş, görsel ve rahatsız edici."],
["A Field in England",2013,6.1,"Ben Wheatley","İç Savaş sırasında kaçan bir grup asker, bir tarlada hazine arayan bir simyacıyla karşılaşır. Siyah beyaz, psychedelic bir folk horror deneyi."],
["The Blood on Satan's Claw",1971,6.2,"Piers Haggard","17. yüzyıl İngiltere'sinde bir çiftçi tuhaf bir kalıntı bulur ve çocuklar, kasabada bir şeytan kültü kurar. Britanya folk horror'ının \"Unholy Trinity\"sinden biri."],
["Black Death",2010,6.4,"Christopher Smith","Ortaçağ İngiltere'sinde veba yayılırken bir keşiş, askerlerle bir bataklık köyüne gider. Köyün vebadan nasıl kurtulduğunu araştırır. Karanlık ve acımasız bir dönem filmi."],
["Men",2022,6.1,"Alex Garland","Yas tutan Harper, kırsalda bir ev kiralar. Köydeki tüm erkekler aynı yüze sahiptir. Alex Garland'ın şiddet ve toksik erkeklik üzerine metaforik korku filmi."],
["Wake Wood",2009,5.9,"David Keating","Çocuklarını kaybeden bir çift, İrlanda'daki bir köyde, ölüleri üç gün diriltme ritüelini öğrenir. Ama kurallar vardır. Hammer'ın yeniden dirilişinden bir folk horror."]],
gore:[
["Cannibal Holocaust",1980,5.7,"Ruggero Deodato","Amazon'da kaybolan bir belgesel ekibini arayan antropolog, bulunan görüntülerde şok edici sahnelere rastlar. Tartışmalı ve yasaklanmış, found footage'ın atalarından biri."],
["Re-Animator",1985,7.2,"Stuart Gordon","Üniversite öğrencisi Herbert West, ölüleri diriltmek için bir serum bulmuştur. Ancak dirilenler öfkeli ve kontrolsüzdür. Lovecraft'tan uyarlanan, kanlı ve komik bir kült film."],
["Evil Dead",2013,6.5,"Fede Álvarez","Beş genç, ormandaki bir kulübede bir kitabı okuyunca kötü ruhları uyandırır. Raimi'nin klasiğinin ciddi ve çok kanlı yeniden çevrimi."],
["Frontier(s)",2007,5.5,"Xavier Gens","Seçim sonrası kaos sırasında Paris'ten kaçan gençler, kırsalda Nazi ideolojisine bağlı bir ailenin eline düşer. Aşırı Fransız korku akımının sert bir örneği."],
["The Devil's Rejects",2005,6.6,"Rob Zombie","Polis baskınından kaçan Firefly ailesi, yolda öldürerek kaçar. Şerif, kardeşinin intikamı için peşlerindedir. 70'ler grindhouse filmi tadında, acımasız bir yol macerası."],
["House of 1000 Corpses",2003,6.0,"Rob Zombie","1977 Cadılar Bayramı'nda yolunu şaşıran iki çift, Firefly ailesinin yaşadığı evde tehlikeli bir geceye düşer. Rob Zombie'nin ilk filmi, kanlı ve kaotik."]],
komedi:[
["Dead Alive",1992,7.3,"Peter Jackson","Sumatra faresi tarafından ısırılan bir kadının dönüşümü ve genç oğlunun saklamaya çalıştığı kabus. Tarihin en kanlı komedilerinden biri."],
["Army of Darkness",1992,7.3,"Sam Raimi","Ash, Ortaçağ'a düşer ve Ölüler Kitabı'nı bulup eve dönmeye çalışır. Burada ölü ordusuyla savaşmak zorundadır. Aksiyon, komedi ve korkuyu kıvamında karıştıran bir devam."],
["Young Frankenstein",1974,8.0,"Mel Brooks","Dr. Frankenstein'ın torunu, dedesinin kalesini miras alır ve yaratığı yeniden canlandırmaya karar verir. Siyah beyaz çekilmiş, klasik canavar filmlerinin ustaca parodisi."],
["Ghostbusters",1984,7.8,"Ivan Reitman","Üç parapsikolog işten çıkarılınca New York'ta hayalet avcılığı işi kurar. Ancak şehre yaklaşan antik bir tanrı vardır. Hem komik hem de bilimkurgu atmosferli, çok sevilen bir klasik."],
["Little Shop of Horrors",1986,6.9,"Frank Oz","Çiçekçide çalışan Seymour, \"Audrey II\" adlı tuhaf bir bitki yetiştirir. Bitki konuşur ve kan ister. Müzikal bir korku-komedi."],
["Housebound",2014,6.8,"Gerard Johnstone","Ev hapsine mahkûm edilen genç Kylie, annesinin evinde yaşarken perili olduğunu fark eder. Yeni Zelanda'dan, sürprizli ve komik bir film."],
["Freaky",2020,6.3,"Christopher Landon","Lise öğrencisi Millie, seri katil Blissfield Butcher ile bedenlerini değiştirir. 24 saati vardır. \"Freaky Friday\" ile slasher'ın eğlenceli karışımı."],
["The Rocky Horror Picture Show",1975,7.4,"Jim Sharman","Yolu kaybolan bir çift, şatoda tuhaf bir bilim insanının partisine düşer. Müzikli, kült film."]],
yaratik:[
["Aliens",1986,8.4,"James Cameron","Ripley, yıllar sonra kayıp koloniye bir grup deniz piyadesiyle gider ve onlarca yaratıkla karşılaşır. Aksiyon ağırlıklı ama son derece gergin bir devam filmi."],
["Predator",1987,7.8,"John McTiernan","Orta Amerika ormanlarında görev yapan bir komando ekibi, görünmez uzaylı bir avcı tarafından izlenmektedir. Arnold Schwarzenegger'li bir aksiyon-korku klasiği."],
["Gojira",1954,7.5,"Ishirō Honda","Nükleer testlerle uyanan dev bir canavar Tokyo'yu yok eder. Japonya'nın savaş travmasını da yansıtan, canavar filmlerinin atası."],
["Creature from the Black Lagoon",1954,6.8,"Jack Arnold","Amazon'da bir fosil arayan bilim insanları, lagünde yaşayan yarı balık, yarı insan bir yaratıkla karşılaşır. Universal canavar serisinin sualtı klasiği."],
["Arachnophobia",1990,6.5,"Frank Marshall","Küçük bir kasabaya gelen ölümcül bir örümcek, hızla çoğalıp insanları tehdit eder. Örümcek korkusu olan bir doktor, onlarla yüzleşmek zorundadır."],
["Crawl",2019,6.1,"Alexandre Aja","Kasırga sırasında Florida'da bir kadın, yaralı babasını bulmak için ev altına girer ve timsahlarla karşılaşır. Hızlı ve gerilimi yüksek bir hayatta kalma filmi."],
["Pitch Black",2000,7.1,"David Twohy","Bir uzay gemisi, yabancı bir gezegene düşer. Gün batımında gezegende yaşayan karanlıktan çıkan yaratıklar saldırır. Vin Diesel'i Riddick olarak tanıtan bilimkurgu korkusu."],
["Trollhunter",2010,6.8,"André Øvredal","Norveçli öğrenciler, bir avcıyı belgelemeye çalışırken trollerin gerçek olduğunu öğrenir. Sahte belgesel tarzında, mizahi ve macera dolu bir yaratık filmi."]],
asya:[
["Kwaidan",1964,8.0,"Masaki Kobayashi","Lafcadio Hearn'ün Japon halk hikâyelerinden uyarlanan dört kısa öykü: hayaletler, kar kadını ve lanetler. Görsel olarak olağanüstü bir antoloji."],
["House (Hausu)",1977,7.0,"Nobuhiko Obayashi","Yedi genç kız, teyzelerinin evine gider ve ev onları yutmaya başlar. Çılgın, renkli ve absürt bir Japon kült korku-komedisi."],
["Tumbbad",2018,8.2,"Rahi Anil Barve","Hindistan'da, ölümsüzlük peşinde bir adam, bir kasabanın kurduğu lanetli bir tanrıyı ve hazineyi keşfeder. Görsel olarak çarpıcı bir Hint folk korku."],
["I Saw the Devil",2010,7.8,"Kim Jee-woon","Bir ajan, eşini öldüren seri katilin peşine düşer ve onu yakalamak yerine kendi intikam oyununu oynar. Çok sert ve acımasız bir Güney Kore gerilimi."],
["Exhuma",2024,6.9,"Jang Jae-hyun","Zengin bir ailenin lanetli mezarını açmak için iki şaman, bir mezar taşçısı ve bir fengşuyi uzmanı bir araya gelir. Koreli geleneksel inançlarla dolu bir doğaüstü gerilim."],
["The Eye",2002,6.6,"Oxide Pang, Danny Pang","Kornea nakli olan genç kız, ameliyat sonrası ölülerin ruhlarını görmeye başlar. Hong Kong yapımı, melankolik bir hayalet hikâyesi."]],
kozmik:[
["Prometheus",2012,7.0,"Ridley Scott","Bir bilim ekibi, insanlığın kökenini bulmak için uzak bir gezegene gider. Ancak orada yaratılışla ilgili korkunç bir gerçek bulurlar. Alien evreninin öncesini anlatır."],
["Life",2017,6.6,"Daniel Espinosa","Uluslararası Uzay İstasyonu mürettebatı, Mars'tan gelen bir örnekten canlı bir organizma çıkarır. Yaratık hızla büyür ve ölümcül hâle gelir."],
["Coherence",2013,7.2,"James Ward Byrkit","Bir kuyruklu yıldız geçerken, bir akşam yemeği partisindeki sekiz arkadaş, gerçekliğin bozulduğunu fark eder. Düşük bütçeli ama zihin bulandıran bir bilimkurgu gerilimi."],
["The Endless",2017,6.4,"Justin Benson, Aaron Moorhead","İki kardeş, bir zamanlar katıldıkları tarikatın kampına geri döner. Yerleşkenin tuhaf, kozmik bir sırrı vardır. Lovecraft esintili ve zeki bir film."],
["Mandy",2018,6.5,"Panos Cosmatos","Ormanda yaşayan çiftin hayatı, bir tarikat lideri yüzünden yıkılır. Red, intikam için çıkar. Nicolas Cage'in çılgın performansıyla, neon renkli bir kâbus."],
["Under the Skin",2013,6.3,"Jonathan Glazer","İskoçya'da erkekleri avlayan bir uzaylı kadın, insan yaşamını gözlemler. Scarlett Johansson'lu, sessiz ve rahatsız edici bir bilimkurgu filmi."],
["Nope",2022,6.8,"Jordan Peele","Kaliforniya'da at çiftliği işleten iki kardeş, gökyüzünde dolaşan tuhaf bir cisimle karşılaşır. Gösteri, bakış ve açgözlülük üzerine, Peele'in üçüncü filmi."],
["Cube",1997,7.2,"Vincenzo Natali","Birbirini tanımayan altı kişi, ölümcül tuzaklarla dolu küp odalardan oluşan bir labirentte uyanır. Kapalı alanda geçen, zihin oyunlu bir film."]],
survival:[
["Eden Lake",2008,6.8,"James Watkins","Bir çift, göl kenarında huzurlu bir hafta sonu geçirmek ister ama yerel gençlerle karşılaşırlar. Küçük bir kavga, korkunç bir kovalamacaya dönüşür. Çok sert ve gerçekçi."],
["Wolf Creek",2005,6.2,"Greg McLean","Avustralya'da üç genç gezgin, arabası bozulunca yardım eden kiracı bir adamla karşılaşır. Adam, gerçek olaylardan esinlenen bir avcıdır."],
["The Hitcher",1986,7.2,"Robert Harmon","Gece yolda otostopçu bir adamı alan genç, adamın acımasız bir katil olduğunu fark eder. Yol boyu devam eden bir kovalamaca."],
["Hush",2016,6.6,"Mike Flanagan","Sağır ve dilsiz yazar Maddie, ormanda yalnız yaşarken maskeli bir saldırganla karşılaşır. Sessizlik içinde geçen bir hayatta kalma gerilimi."],
["The Platform",2019,7.0,"Galder Gaztelu-Urrutia","Dikey bir hapishanede, yemekle dolu bir platform katlardan aşağıya iner. Üst katlar yer, alt katlar aç kalır. Sınıf ve açgözlülük üzerine sert bir alegori."],
["Speak No Evil",2022,6.8,"Christian Tafdrup","Bir Danimarkalı aile, tatilde tanıştıkları Hollandalı çiftin evinde hafta sonu geçirmeye gider. Nazik davranmaya çalışmak, onları tuzağa düşürür."],
["Triangle",2009,6.8,"Christopher Smith","Bir tekne gezisinde fırtınaya yakalanan grup, gizemli bir gemiye sığınır. Gemide, zaman döngüsü gibi bir şey yaşanır. Zihin açıcı bir gerilim."],
["Bird Box",2018,6.6,"Susanne Bier","Dışarıda görülenin insanları öldürdüğü bir dünyada, Malorie çocuklarıyla gözleri bağlı bir şekilde nehirde yolculuk eder. Sandra Bullock'lu bir felaket gerilimi."]],
gotik:[
["Dr. Jekyll and Mr. Hyde",1931,7.6,"Rouben Mamoulian","Saygın doktor Jekyll, içindeki kötülüğü açığa çıkaran bir iksir geliştirir. Hyde olarak ortalığı kasıp kavurur. Stevenson'ın romanının ilk büyük ses film uyarlaması."],
["The Phantom of the Opera",1925,7.6,"Rupert Julian","Paris Operası'nın altında yaşayan maskeli bir hayalet, genç bir şarkıcıya takıntılıdır. Lon Chaney'in kendi makyajıyla yarattığı ikonik bir sessiz film."],
["The Wolf Man",1941,7.2,"George Waggner","Larry Talbot, bir kurt adam tarafından ısırılır ve her dolunayda dönüşür. Universal'ın canavar serisinin kurt adam klasiği."],
["Black Sunday",1960,7.1,"Mario Bava","Yüzyıllar önce cadılıkla yargılanıp idam edilen prenses, mezarından kalkıp intikam almaya gelir. Bava'nın siyah beyaz, görsel olarak hayranlık uyandıran gotik filmi."],
["Eyes Without a Face",1960,7.7,"Georges Franju","Dr. Génessier, yüzü yanmış kızına yeni bir yüz yapmak için genç kadınları kaçırır. Şiirsel ve ürkütücü bir Fransız korku klasiği."],
["Pan's Labyrinth",2006,8.2,"Guillermo del Toro","İç Savaş sonrası İspanya'da Ofelia, üvey babasının askerî evinde bir labirent ve gizemli bir faun keşfeder. Hem karanlık bir peri masalı hem de savaş dramı."],
["Sleepy Hollow",1999,7.3,"Tim Burton","New York polisi Ichabod Crane, bir köyde başsız bir atlının işlediği cinayetleri araştırır. Johnny Depp'li, Burton imzalı gotik atmosferli bir film."],
["Carnival of Souls",1962,7.0,"Herk Harvey","Bir araba kazasından kurtulan kadın, hayaletimsi bir figür görmeye başlar ve terk edilmiş bir lunaparka çekilir. Düşük bütçeli, ürkütücü bir kült."]]
};
