/* Seri filmleri: devam filmleri, ön hikâyeler, yeniden çevrimler. Biçim: [ad, yıl, imdb, yönetmen, açıklama] */
(function(){
const S={
slasher:[
["Halloween II",1981,6.5,"Rick Rosenthal","İlk filmin aynı gecesinde Michael Myers, yaralı Laurie'yi bulmak için Haddonfield hastanesine girer. Kovalamaca hastane koridorlarında devam eder."],
["Halloween III: Season of the Witch",1982,4.7,"Tommy Lee Wallace","Michael Myers'ı bir kenara bırakan seri, bu kez bir oyuncak şirketinin Cadılar Bayramı maskeleriyle planladığı kitlesel bir cinayeti anlatır. Serinin tuhaf bir antoloji denemesi."],
["Halloween 4: The Return of Michael Myers",1988,5.8,"Dwight H. Little","Yıllarca komada kalan Michael uyanır ve yeğeni küçük Jamie'yi öldürmek için Haddonfield'a döner. Dr. Loomis yine peşindedir."],
["Halloween 5: The Revenge of Michael Myers",1989,5.2,"Dominique Othenin-Girard","Michael hayatta kalmıştır ve Jamie ile gizemli bir bağı vardır. Kasabada tekrar cinayetler başlar, Loomis son bir mücadeleye hazırlanır."],
["Halloween: The Curse of Michael Myers",1995,4.9,"Joe Chappelle","Michael'ın cinayetlerinin ardında bir kült ve eski bir lanet olduğu ortaya çıkar. Serinin karanlık mitolojisini derinleştiren bir bölüm."],
["Halloween H20: 20 Years Later",1998,5.7,"Steve Miner","Laurie Strode, 20 yıl sonra sahte bir kimlikle yaşarken kendi oğlu için yine Michael ile yüzleşir. İlk iki filmin devamı olarak yazılmıştır."],
["Halloween: Resurrection",2002,3.9,"Rick Rosenthal","Bir grup genç, Michael Myers'ın çocukluk evinde canlı yayınlanan bir reality show çekiminde mahsur kalır."],
["Halloween",2007,6.0,"Rob Zombie","Rob Zombie'nin yorumuyla Michael'ın çocukluğu ve ailesi, katil olma sürecinin kökeni anlatılır ve ilk filmin hikâyesi yeniden çekilir."],
["Halloween II",2009,4.7,"Rob Zombie","Zombie'nin ikinci filminde Laurie, olaydan sonra kâbuslar ve halüsinasyonlarla boğuşurken Michael yine geri döner."],
["Halloween",2018,6.5,"David Gordon Green","Laurie Strode, 40 yıl sonra Michael ile yüzleşmeye hazırdır. Bu film, 1978'deki ilk filmin doğrudan devamıdır ve diğer devam filmlerini yok sayar."],
["Halloween Kills",2021,5.5,"David Gordon Green","Haddonfield halkı, Michael Myers'a karşı birleşir. Laurie hastanedeyken kasaba öfkeli bir kalabalığa dönüşür."],
["Halloween Ends",2022,4.6,"David Gordon Green","Michael'la son hesaplaşmadan önce Haddonfield'ın dört yıl sonraki hayatı anlatılır. Laurie ve genç bir adamın hikâyesi, serinin kapanışı olur."],
["A Nightmare on Elm Street 2: Freddy's Revenge",1985,5.4,"Jack Sholder","Yeni eve taşınan bir genç, Freddy tarafından ele geçirilir. Freddy, onun bedenini kullanarak gerçek dünyaya çıkmaya çalışır."],
["A Nightmare on Elm Street 3: Dream Warriors",1987,6.6,"Chuck Russell","Freddy'nin hayatta kalan son çocuklarını tedavi eden kliniktekiler, rüyalarında kendi güçlerini kullanarak ona karşı birleşir. Serinin en sevilen filmlerinden."],
["A Nightmare on Elm Street 4: The Dream Master",1988,5.7,"Renny Harlin","Kimberly, arkadaşlarının güçlerini bir araya getirerek Freddy'yi yeniden yok etmeye çalışır. Yaratıcı ölüm sahneleriyle bol aksiyonlu bir devam."],
["A Nightmare on Elm Street 5: The Dream Child",1989,4.9,"Stephen Hopkins","Alice'in doğmamış çocuğu, Freddy'nin yeni yolu hâline gelir. Freddy bu kez bebeğin rüyalarını kullanır."],
["Freddy's Dead: The Final Nightmare",1991,4.9,"Rachel Talalay","Freddy, Springwood'da hayatta kalan son çocuğu bulmak için peşine düşer. Serinin sözde final filmi, 3D sahneleriyle de bilinir."],
["Wes Craven's New Nightmare",1994,6.4,"Wes Craven","Freddy'yi canlandıran oyuncular ve yapımcılar, gerçek hayatta Freddy'nin ortaya çıktığını fark eder. Seriyi kendi üzerine düşündüren zekice bir film."],
["Freddy vs. Jason",2003,5.8,"Ronny Yu","Güç kaybeden Freddy, Jason'ı Springwood'a gönderir ve iki ikonik katil karşı karşıya gelir."],
["A Nightmare on Elm Street",2010,5.2,"Samuel Bayer","Orijinal filmin yeniden çevrimi: gençler aynı kâbus katilini rüyalarında görür ve uyumamaya çalışır."],
["Friday the 13th Part 2",1981,6.0,"Steve Miner","Birinci filmden iki yıl sonra Crystal Lake yakınında yeni bir kamp danışmanları grubu, Jason Voorhees'in hedefi olur. Jason ilk kez onların arasında."],
["Friday the 13th Part III",1982,5.7,"Steve Miner","Jason, bir grup gencin tatil çiftliğine saldırır ve ikonik hokey maskesini bu filmde takar."],
["Friday the 13th: The Final Chapter",1984,6.1,"Joseph Zito","Jason'ı sonsuza dek yok etmek isteyen bir ailenin ve genç Tommy Jarvis'in hikâyesi. Serinin sözde final filmi."],
["Friday the 13th: A New Beginning",1985,4.7,"Danny Steinmann","Tommy Jarvis travma sonrası bir ruh sağlığı merkezinde yaşarken yeni cinayetler başlar. Kimin yaptığı konusu tartışmalıdır."],
["Friday the 13th Part VI: Jason Lives",1986,6.0,"Tom McLoughlin","Tommy Jarvis, Jason'ı bir kez ve herkes için gömmek ister ama yıldırım onu geri getirir. Mizahı bol ve eğlenceli bir devam."],
["Friday the 13th Part VII: The New Blood",1988,5.3,"John Carl Buechler","Telekinetik güçlü bir genç kız, Jason'ı yanlışlıkla uyandırır. Carrie esintili bir Jason macerası."],
["Friday the 13th Part VIII: Jason Takes Manhattan",1989,4.6,"Rob Hedden","Jason, bir lise mezuniyet gemisiyle New York'a gelir. Filmin büyük kısmı gemide geçer."],
["Jason Goes to Hell: The Final Friday",1993,4.4,"Adam Marcus","Jason'ın ruhu başkalarının bedenine geçerek yaşar ve kendi ailesinden birini arar."],
["Jason X",2001,4.5,"James Isaac","Jason, 25. yüzyılda uzay gemisinde buzdan kurtarılır ve bu kez uzaylı bir ortamda öldürmeye devam eder."],
["Friday the 13th",2009,5.5,"Marcus Nispel","Serinin yeniden çevrimi: gençler Crystal Lake'te kaybolan arkadaşlarını ararken Jason'la karşılaşır."],
["Scream 2",1997,6.1,"Wes Craven","İlk olayın ardından Sidney'in kolejinde, ilk filmden uyarlanan bir film gösterimiyle birlikte yeni cinayetler başlar."],
["Scream 3",2000,5.6,"Wes Craven","Hollywood'da \"Stab 3\" çekimi sırasında oyuncular, kendi rollerini oynarken öldürülür. Sidney yine hedeftir."],
["Scream 4",2011,6.2,"Wes Craven","Sidney, kitap turu için Woodsboro'ya döner ve yeni nesil gençlerin korku filmi çağında yeni bir katille karşılaşır."],
["Scream",2022,6.3,"Matt Bettinelli-Olpin, Tyler Gillett","Yeniden başlayan Ghostface cinayetleri, eski karakterleri ve yeni bir gençler grubunu bir araya getirir."],
["Scream VI",2023,6.1,"Matt Bettinelli-Olpin, Tyler Gillett","Hayatta kalanlar New York'a taşınır ama Ghostface onları orada da bulur. Seri, ilk kez Woodsboro dışında geçer."],
["The Texas Chainsaw Massacre 2",1986,5.5,"Tobe Hooper","Bir radyo spikeri, Leatherface ve ailesinin kanlı bir yuvaya dönüşen yeraltı mekânına girer. İlk filmden çok daha komik ve abartılı bir devam."],
["Leatherface: The Texas Chainsaw Massacre III",1990,5.0,"Jeff Burr","Yolculuk yapan bir çift, Teksas'ta Leatherface'in yeni ailesinin eline düşer."],
["The Texas Chainsaw Massacre",2003,6.2,"Marcus Nispel","Orijinal filmin yeniden çevrimi: gençler Teksas'ta yolda yardım ararken Leatherface'in ailesiyle karşılaşır."],
["The Texas Chainsaw Massacre: The Beginning",2006,5.9,"Jonathan Liebesman","2003 filminin ön hikâyesi: Leatherface'in nasıl bu hâle geldiği ve ailesinin kökeni anlatılır."],
["Texas Chainsaw 3D",2013,4.8,"John Luessenhop","Orijinal filmden devam eden bir hikâyede, Leatherface'in akrabası olduğunu yeni öğrenen bir kadın Teksas'a gelir."],
["Leatherface",2017,5.0,"Alexandre Bustillo, Julien Maury","Leatherface'in gençliği ve onu nasıl bir katil hâline getiren olaylar anlatılır."],
["Texas Chainsaw Massacre",2022,4.1,"David Blue Garcia","Leatherface, yıllar sonra terk edilmiş bir kasabada gençlerin karşısına çıkar. Orijinal filmin devamı olarak çekilmiştir."],
["Child's Play 2",1990,5.8,"John Lafia","Chucky yeniden dirilir ve yetim kalan Andy'nin ardından koruyucu ailesine gider."],
["Child's Play 3",1991,5.3,"Jack Bender","Andy genç bir askeri okulda yaşarken Chucky bir kez daha peşine düşer."],
["Bride of Chucky",1998,5.9,"Ronny Yu","Chucky'yi diriltmek isteyen eski sevgilisi Tiffany, ona bir eş olur. Seriyi komik ve kara mizahlı bir yöne çeviren film."],
["Seed of Chucky",2004,4.9,"Don Mancini","Chucky ve Tiffany'nin oğlu Glen/Glenda, ebeveynlerini diriltir ve Hollywood'da yeni bir kaosa yol açar."],
["Curse of Chucky",2013,5.6,"Don Mancini","Nica adlı tekerlekli sandalyedeki bir kadının evine gelen kutuda Chucky vardır. Seri, korku köklerine döner."],
["Cult of Chucky",2017,5.2,"Don Mancini","Nica bir akıl hastanesinde tedavi görürken Chucky yeniden ortaya çıkar. Hem eski karakterleri hem yeni olayları birleştirir."],
["Child's Play",2019,6.0,"Lars Klevberg","Orijinalin yeniden çevrimi: yapay zekâlı bir oyuncak bebek, çocuğuyla bağ kurarken kontrolden çıkar."],
["Candyman: Farewell to the Flesh",1995,5.0,"Bill Condon","Candyman'in lanetli hikâyesi New Orleans'ta devam eder ve yeni bir kurban onun geçmişiyle yüzleşir."],
["Candyman",2021,5.9,"Nia DaCosta","Chicago'nun Cabrini-Green bölgesinde bir ressam, Candyman efsanesinin yeniden uyanışına tanık olur. 1992 filminin devamıdır."],
["Final Destination 2",2003,6.0,"David R. Ellis","Bir otoyol kazası önceden görülür ve kurtulanlar, Ölüm'ün yeni listesinden kaçmaya çalışır."],
["Final Destination 3",2006,5.8,"James Wong","Bir lunapark treni kazasında ölmesi gereken gençler, fotoğraflardaki ipuçlarıyla kaderlerini değiştirmeye çalışır."],
["The Final Destination",2009,5.2,"David R. Ellis","Bir yarış pistinde yaşanan kazadan kurtulanlar, Ölüm'ün planına karşı yeniden direnir."],
["Final Destination 5",2011,5.8,"Steven Quale","Köprü çökmesinden kurtulan çalışanlar yine Ölüm'ün listesindedir. Serinin sürpriz finaliyle ünlü bölümü."],
["Final Destination: Bloodlines",2025,6.5,"Zach Lipovsky, Adam B. Stein","Bir kadın, ailesini ve kendini ölümden kurtarmak için nesiller öncesine uzanan bir lanetin izini sürer."],
["Terrifier 3",2024,6.0,"Damien Leone","Art the Clown, Noel'de yeniden katliama girişir ve Sienna'yla hesaplaşması devam eder."],
["Happy Death Day 2U",2019,6.3,"Christopher Landon","Tree, bu kez paralel evrenlerde zaman döngüsüne düşer. Korkudan çok bilimkurgu ve komediye kayan bir devam."],
["MaXXXine",2024,6.2,"Ti West","1985 Los Angeles'ında yıldız olmak isteyen Maxine, geçmişi ve bir seri katilin gölgesiyle yüzleşir. X üçlemesinin finali."],
["Black Christmas",2006,4.5,"Glen Morgan","1974 filminin yeniden çevrimi: yılbaşında bir kız yurdunda bir katil ortaya çıkar."],
["Black Christmas",2019,3.9,"Sophia Takal","Yeni bir kız yurdunda, üniversite öğrencileri tuhaf bir tarikatın hedefi olur."]],
hayalet:[
["Annabelle",2014,5.4,"John R. Leonetti","Conjuring evreninin ilk yan filmi: lanetli bir bebeğin sahibi, evine yerleşen karanlık güçle mücadele eder."],
["Annabelle: Creation",2017,6.5,"David F. Sandberg","Bebeğin kökeni anlatılır: bir yetimhane evinde kız çocuklarını korkunç bir ruh takip eder."],
["Annabelle Comes Home",2019,5.9,"Gary Dauberman","Warren'ların eşya odasında uyanan lanetli nesneler, genç bir kızı ve arkadaşlarını tehdit eder."],
["The Nun",2018,5.3,"Corin Hardy","Romanya'daki bir manastırda genç bir rahibe ve bir rahip, ürkütücü bir ölümün ardındaki şeytani gücü araştırır."],
["The Curse of La Llorona",2019,5.3,"Michael Chaves","Ağlayan kadın efsanesi, bir sosyal hizmet uzmanının ailesini tehdit eder. Conjuring evreninin bir yan filmi."],
["The Conjuring: The Devil Made Me Do It",2021,6.3,"Michael Chaves","Warren çifti, bir cinayet davasında şeytani etkiyi kanıtlamaya çalışır."],
["The Conjuring: Last Rites",2025,6.2,"Michael Chaves","Ed ve Lorraine Warren'ın son büyük vakası, onları ailenin geçmişindeki karanlık bir sırra götürür."],
["Insidious: Chapter 2",2013,6.5,"James Wan","Lambert ailesi, ilk filmdeki olayların ardından Öte Âlem'den gelen yeni bir tehditle yüzleşir."],
["Insidious: Chapter 3",2015,6.1,"Leigh Whannell","Elise Rainier, bir genç kızı rahatsız eden varlığı yenmek için ilk kez ön plana çıkar. Serinin ön hikâyesi."],
["Insidious: The Last Key",2018,5.7,"Adam Robitel","Elise, çocukluk evinde ortaya çıkan bir ruh yüzünden geçmişiyle yüzleşir."],
["Insidious: The Red Door",2023,5.7,"Patrick Wilson","Josh ve oğlu Dalton, aile travmasının izlerini ve Öte Âlem'in son sırlarını çözmek zorundadır."],
["Poltergeist II: The Other Side",1986,5.8,"Brian Gibson","Freeling ailesi yeni bir eve taşınır ama ruhlar onları takip eder. Bu kez bir din adamı da vardır."],
["Poltergeist III",1988,4.7,"Gary Sherman","Carol Anne, Şikago'daki bir gökdelende amcasının yanında kalırken ruhlar tekrar ortaya çıkar."],
["Poltergeist",2015,4.7,"Gil Kenan","Orijinal filmin yeniden çevrimi: banliyödeki aile, çocuklarını kaçıran ruhlarla savaşır."],
["Sinister 2",2015,5.3,"Ciarán Foy","Bu kez bir anne ve iki oğlu, Bughuul'un çocuklara dönük kötülüğüne karşı kaçar."],
["Smile 2",2024,6.6,"Parker Finn","Şöhretin zirvesindeki bir pop yıldızı, gülümseyen varlığın lanetiyle karşılaşır. İlk filmin devamı."],
["The Haunting",1999,4.9,"Jan de Bont","1963 klasiğinin yeniden çevrimi: bir grup insan, uykusuzluk araştırması için lanetli Hill House'a gelir."],
["The Woman in Black: Angel of Death",2014,4.4,"Tom Harper","İkinci Dünya Savaşı'nda, çocukları taşıyan bir okul, Eel Marsh House'a sığınır ve siyahlı kadınla yüzleşir."]],
seytani:[
["Exorcist II: The Heretic",1977,3.8,"John Boorman","Regan'ın bir psikiyatrist tarafından incelendiği, ilk filmin atmosferine pek benzemeyen bir devam."],
["Exorcist: The Beginning",2004,5.1,"Renny Harlin","Peder Merrin'in gençliği ve Afrika'da bulunan kadim bir kilisede şeytanla ilk karşılaşması anlatılır."],
["Dominion: Prequel to the Exorcist",2005,5.0,"Paul Schrader","Aynı hikâyenin Paul Schrader versiyonu: Merrin'in imanının sınandığı daha yavaş ve düşünceli bir ön film."],
["The Exorcist: Believer",2023,4.8,"David Gordon Green","İki genç kızın aynı anda ele geçirilmesiyle, babanın Chris MacNeil'den yardım istediği ilk filmin devamı."],
["Damien: Omen II",1978,6.1,"Don Taylor","Damien artık bir genç ve amcasının ailesiyle yaşarken kendi gücünün farkına varır."],
["Omen III: The Final Conflict",1981,5.3,"Graham Baker","Yetişkin Damien, bir siyasi lider olarak dünyayı ele geçirmeye çalışırken İsa'nın dönüşü yaklaşır."],
["The Omen",2006,5.4,"John Moore","1976 filminin yeniden çevrimi: bir diplomat, oğlunun Deccal olduğundan şüphelenir."],
["The First Omen",2024,6.2,"Arkasha Stevenson","Roma'da bir yetimhanede çalışmaya gelen genç bir rahibe, Deccal'in doğuşunu hazırlayan planı keşfeder."],
["Suspiria",2018,6.7,"Luca Guadagnino","1977 filminin yeniden yorumu: Berlin'de bir dans akademisinin arkasında cadı kültü yatar."]],
zombi:[
["Night of the Living Dead",1990,6.9,"Tom Savini","1968 filminin yeniden çevrimi: bir grup insan, ölülerin dirildiği gece bir çiftlik evine kapanır."],
["Land of the Dead",2005,6.2,"George A. Romero","Zombiler dünyayı ele geçirmişken, hayatta kalanlar zenginlerin korunan bir gökdelen şehrinde yaşar."],
["Diary of the Dead",2007,5.5,"George A. Romero","Film öğrencileri, salgının ilk günlerini kamerayla kaydeder."],
["Survival of the Dead",2009,5.0,"George A. Romero","Bir adada iki aile, zombileri öldürmek mi yoksa saklamak mı konusunda çatışır."],
["Return of the Living Dead Part II",1988,5.3,"Ken Wiederhorn","Yanlışlıkla açılan askeri kimyasal bu kez bir banliyöyü etkiler."],
["Return of the Living Dead 3",1993,5.8,"Brian Yuzna","Bir askeri çocuğun sevgilisi, kazada ölünce onu zombi olarak diriltir. Romantik ve acı bir zombi hikâyesi."],
["Seoul Station",2016,6.1,"Yeon Sang-ho","Train to Busan'ın animasyon ön hikâyesi: salgın Seul istasyonunda başlar."],
["Train to Busan Presents: Peninsula",2020,5.3,"Yeon Sang-ho","Salgından dört yıl sonra, Kore yarımadasında bırakılan paranın peşinde bir ekip kasabada zombilerle ve silahlı gruplarla karşılaşır."],
["28 Years Later",2025,6.8,"Danny Boyle","Öfke virüsünden 28 yıl sonra bir adaya sığınan topluluktan bir çocuk, anakaraya geçerek yeni bir dünyayla karşılaşır."]],
vampir:[
["Queen of the Damned",2002,5.3,"Michael Rymer","Vampir Lestat'ın rock yıldızı olarak uyandırdığı kadim vampir kraliçe Akasha, dünyayı ele geçirmek ister."],
["Blade II",2002,6.7,"Guillermo del Toro","Blade, vampirlerle ittifak yaparak vampirleri avlayan daha ölümcül bir türle savaşır."],
["Blade: Trinity",2004,5.8,"David S. Goyer","Blade, bu kez FBI tarafından aranırken ilk vampir Drake'i ve onunla savaşacak avcıları bulur."],
["From Dusk Till Dawn 2: Texas Blood Money",1999,5.2,"Scott Spiegel","Bir grup soyguncu, Meksika sınırındaki bir banka soygunu için vampir dolu bir barda saklanır."],
["From Dusk Till Dawn 3: The Hangman's Daughter",2000,5.3,"P.J. Pesce","1913'te, kaçak bir grup Meksika'da vampirlerin yuvası olan bir köye gelir."],
["30 Days of Night: Dark Days",2010,4.6,"Ben Ketai","Stella, Barrow'daki felaketten sonra vampirlere karşı intikam peşinde Los Angeles'a gider."],
["Ginger Snaps 2: Unleashed",2004,6.5,"Brett Sullivan","Brigitte, kurt adam lanetini yavaşlatmak için bir rehabilitasyon merkezine girer ve yeni bir canavar peşindedir."],
["Ginger Snaps Back: The Beginning",2004,6.3,"Grant Harvey","19. yüzyıl Kanada'sında iki kız kardeşin ve bir kalenin kurt adam lanetini anlatan bir ön hikâye."],
["An American Werewolf in Paris",1997,5.1,"Anthony Waller","Paris'te tatil yapan genç Amerikalılar, kurt adam topluluğuyla karşılaşır."],
["Fright Night Part 2",1988,6.0,"Tommy Lee Wallace","Charley, vampir Jerry Dandridge'in kız kardeşi Regine'le yüzleşirken yeniden tehdit altındadır."],
["Fright Night",2011,6.4,"Craig Gillespie","1985 filminin yeniden çevrimi: Las Vegas'ta genç bir adam, yeni komşusunun vampir olduğunu fark eder."],
["The Brides of Dracula",1960,6.8,"Terence Fisher","Van Helsing, Transilvanya'da genç bir öğretmenin peşindeki baron vampiri durdurmaya çalışır."],
["Dracula: Prince of Darkness",1966,6.4,"Terence Fisher","Dracula'nın şatosuna yolculuk eden iki çift, Kont'un yeniden dirilişine yol açar."]],
psikolojik:[
["Psycho II",1983,6.5,"Richard Franklin","Norman Bates, yıllar sonra serbest bırakılır ve Bates Motel'e döner. Ama çevresindeki tuhaf olaylar yine başlar."],
["Psycho III",1986,5.5,"Anthony Perkins","Norman bir kadına âşık olurken annesinin sesi yine duyulur. Anthony Perkins'in yönettiği bir devam."],
["Psycho IV: The Beginning",1990,5.9,"Mick Garris","Norman, bir radyo programına telefonla bağlanarak çocukluğunu ve annesiyle ilişkisini anlatır."],
["Psycho",1998,4.6,"Gus Van Sant","Hitchcock filminin renkli ve neredeyse kare kare yeniden çevrimi."],
["Manhunter",1986,7.2,"Michael Mann","FBI ajanı Will Graham, seri katil Francis Dolarhyde'ı yakalamak için Hannibal Lecter'dan yardım ister."],
["Hannibal",2001,6.8,"Ridley Scott","Sessiz Kuzular'dan on yıl sonra Clarice Starling, kaçak Hannibal Lecter'ın izini sürer."],
["Red Dragon",2002,7.2,"Brett Ratner","Will Graham, Hannibal Lecter'ın yardımıyla yeni bir seri katili arar."],
["Hannibal Rising",2007,6.2,"Peter Webber","Genç Hannibal'ın savaşta ailesini kaybetmesi ve intikam arayışı, onun nasıl bir canavara dönüştüğünü anlatır."],
["Doctor Sleep",2019,7.3,"Mike Flanagan","Yetişkin Danny Torrance, ruh yiyen bir tarikatla savaşırken Overlook Oteli'ne geri döner. The Shining'in devamı."],
["Carrie",2013,5.9,"Kimberly Peirce","1976 filminin yeniden çevrimi: dışlanmış bir genç kızın telekinetik güçleri balo gecesi patlar."],
["The Rage: Carrie 2",1999,4.6,"Katt Shea","Carrie'ye benzer güçleri olan başka bir genç kız, lise zorbalarına karşı koyar."],
["Black Phone 2",2025,6.0,"Scott Derrickson","Finney ve kız kardeşi Gwen, kaçıran katilin karanlık bir uzantısıyla yine karşılaşır."]],
foundfootage:[
["Book of Shadows: Blair Witch 2",2000,4.0,"Joe Berlinger","Blair Witch hayranları ormana tur yaparak giderler ve olaylar kontrolden çıkar."],
["Blair Witch",2016,5.1,"Adam Wingard","Kayıp kız kardeşini arayan bir adam, ormanda yine cadının efsanesiyle karşılaşır."],
["Paranormal Activity 2",2010,5.7,"Tod Williams","İlk filmin ailesinden başka bir aile de evinde aynı tuhaf olayları yaşar."],
["Paranormal Activity 3",2011,5.2,"Henry Joost, Ariel Schulman","Serinin geçmişine dönülür ve çocukken yaşanan musallat anlatılır."],
["Paranormal Activity 4",2012,4.6,"Henry Joost, Ariel Schulman","Komşu çocuğuyla birlikte yaşayan bir ailenin evinde, Xbox kameralarıyla kaydedilen olaylar."],
["Paranormal Activity: The Marked Ones",2014,5.0,"Christopher Landon","Los Angeles'ta bir komşunun ölümü sonrası, genç bir adam şeytani bir izi taşımaya başlar."],
["Paranormal Activity: The Ghost Dimension",2015,4.6,"Gregory Plotkin","Bir aile, özel bir kamerayla görünmeyen varlığı görmeyi başarır."],
["Paranormal Activity: Next of Kin",2021,5.0,"William Eubank","Bir kadın, Amish bir topluluğun içinde kayıp ailesini ararken tuhaf bir ritüelle karşılaşır."],
["[REC]²",2009,6.5,"Jaume Balagueró, Paco Plaza","Bir polis timi, ilk filmdeki karantinalı apartmana girer ve enfeksiyonun şeytani kökenini keşfeder."],
["[REC]³ Génesis",2012,5.3,"Paco Plaza","Bir düğün gününde enfeksiyon başlar ve gelin ile damat birbirini kurtarmaya çalışır."],
["[REC]⁴: Apocalipsis",2014,5.2,"Jaume Balagueró","Ángela, bir gemide karantina altındayken serinin sonu getirilir."],
["V/H/S/2",2013,6.1,"Çeşitli yönetmenler","Dedektifler, yeni VHS kasetlerini izlemeye başlar ve çok daha tuhaf hikâyelere şahit olur."],
["V/H/S: Viral",2014,4.2,"Çeşitli yönetmenler","Bir internet videosu viral olurken, farklı hikâyeler birbirine bağlanır."],
["V/H/S/94",2021,5.8,"Çeşitli yönetmenler","1994'te bir SWAT ekibi, bir deponun içinde bulunan kasetlerdeki dehşeti izler."],
["V/H/S/85",2023,5.3,"Çeşitli yönetmenler","1985'e ait kasetlerde birbirinden bağımsız korku hikâyeleri anlatılır."],
["V/H/S/99",2022,5.4,"Çeşitli yönetmenler","Y2K döneminin kasetlerinden oluşan yeni bir korku antolojisi."],
["Hell House LLC II: The Abaddon Hotel",2018,5.3,"Stephen Cognetti","Gazeteciler, ilk filmin otelinde olanları anlamak için tekrar içeri girer."],
["Hell House LLC III: Lake of Fire",2019,5.0,"Stephen Cognetti","Abaddon Hotel'de bulunan eşyalarla yapılan bir sergi, tekrar kötülüğü uyandırır."],
["Creep 2",2017,6.3,"Patrick Brice","Genç bir kadın, internet ilanıyla çağırdığı garip adamla güvenli bir mesafe bırakmaya çalışır."],
["Grave Encounters 2",2012,5.0,"John Poliquin","Bir film öğrencisi, ilk filmin gerçek olup olmadığını araştırmak için kapalı hastaneye gider."],
["Unfriended: Dark Web",2018,6.0,"Stephen Susco","Bir genç, bilgisayarında yeni aldığı laptop'un içindeki gizli dosyalarla karanlık bir ağın tuzağına düşer."],
["The Last Exorcism Part II",2013,4.0,"Ed Gass-Donnelly","Nell, ilk filmin olaylarının ardından yeni bir hayata başlamaya çalışırken şeytani varlık peşini bırakmaz."],
["The Cloverfield Paradox",2018,5.5,"Julius Onah","Uzay istasyonundaki mürettebat, enerji kaynağı denemesi sonrası farklı gerçeklik katmanlarına düşer."]],
body:[
["The Fly II",1989,5.1,"Chris Walas","Seth Brundle'ın oğlu Martin, babasının mirasını taşıyarak hızla büyür ve kendi dönüşümüne başlar."],
["The Thing",2011,6.2,"Matthijs van Heijningen Jr.","1982 filminden önce, Norveçli bir ekibin Antarktika'da buluduğu uzaylı yaratığın hikâyesi."],
["Rabid",2019,5.0,"Jen Soska, Sylvia Soska","Cronenberg'in 1977 filminin yeniden çevrimi: yüzü kazada yaralanan bir moda tasarımcısı, deneysel bir tedaviyle değişir."]],
folk:[
["The Wicker Man",2006,3.7,"Neil LaBute","1973 filminin Amerikan yeniden çevrimi: bir polis, kayıp bir kızı aramak için ıssız bir adaya gider."]],
gore:[
["The Hills Have Eyes Part II",1984,3.9,"Wes Craven","İlk filmin hayatta kalanları, bir motokros takımıyla çöle döner ve mutantlarla tekrar karşılaşır."],
["The Hills Have Eyes",2006,6.4,"Alexandre Aja","Nükleer test bölgesinde mahsur kalan aile, mutantların eline düşer. Alexandre Aja'nın yeniden çevrimi."],
["The Hills Have Eyes II",2007,5.1,"Martin Weisz","Bir grup askeri stajyer, çöldeki mutantlarla savaşmak zorunda kalır."],
["Saw II",2005,6.6,"Darren Lynn Bousman","Jigsaw'ın yeni oyununda sekiz kişi, zehirli gazla dolu bir evde kilitli kalır."],
["Saw III",2006,6.2,"Darren Lynn Bousman","Jigsaw, hasta yatağında çaresiz bir cerrahı ölümcül bir oyuna sürükler."],
["Saw IV",2007,5.8,"Darren Lynn Bousman","Jigsaw'ın ölümünden sonra bir polis, yeni bir oyuna dahil olur."],
["Saw V",2008,5.6,"David Hackl","Jigsaw'ın yeni yardımcısı, FBI ajanı Hoffman'ın peşine düşer."],
["Saw VI",2009,5.9,"Kevin Greutert","Bir sigorta yöneticisi, ölüm ve hayat arasındaki kararlarının hesabını verir."],
["Saw 3D",2010,5.5,"Kevin Greutert","Hoffman, hayatta kalan eski kurbanlara karşı yeni bir oyun kurar."],
["Jigsaw",2017,5.8,"Michael Spierig, Peter Spierig","Jigsaw ölümünden yıllar sonra tekrar tuzaklar kurmaya başlar. Katil kim?"],
["Spiral: From the Book of Saw",2021,5.2,"Darren Lynn Bousman","Bir dedektif, Jigsaw tarzı yeni bir seri katilin cinayetlerini araştırır."],
["Saw X",2023,6.5,"Kevin Greutert","John Kramer, sahte bir kanser tedavisiyle onu kandıranlardan intikam alır."],
["Hostel: Part II",2007,5.5,"Eli Roth","Bu kez üç kadın turist, aynı örgüt tarafından hedef alınır."],
["Hostel: Part III",2011,4.7,"Scott Spiegel","Las Vegas'ta bir bekârlığa veda partisi, ölüm oyunlarına sahne olur."],
["Evil Dead Rise",2023,6.5,"Lee Cronin","Los Angeles'ta bir apartman dairesinde, Ölüler Kitabı'nın tekrar açılması bir anne ve çocuklarına musallat olur."],
["3 from Hell",2019,5.0,"Rob Zombie","Firefly ailesi, hapisten çıkarak tekrar kanlı bir yol serüvenine başlar."],
["Bride of Re-Animator",1989,6.0,"Brian Yuzna","Herbert West ve Dan Cain, ölümü yenme deneylerini ceset parçalarıyla sürdürür."],
["Beyond Re-Animator",2003,5.6,"Brian Yuzna","West, hapisteyken bir ceza infaz memuru olan eski bir asistanıyla yeni deneyler yapar."]],
komedi:[
["Gremlins 2: The New Batch",1990,6.3,"Joe Dante","Gizmo New York'ta ofis binasına düşer ve gremlinler yeniden çoğalır."],
["Beetlejuice Beetlejuice",2024,6.7,"Tim Burton","Lydia'nın kızı yüzünden Beetlejuice'ın adı yeniden anılır ve ailesi yine ölüler dünyasına karışır."],
["Ghostbusters II",1989,6.6,"Ivan Reitman","New York'ta bir sihirli pembe sıvı, şehrin ruhlarını tekrar harekete geçirir."],
["Ghostbusters",2016,5.2,"Paul Feig","Dört kadın bilim insanı, New York'ta ortaya çıkan hayaletlere karşı hayalet avcılığı yapar."],
["Ghostbusters: Afterlife",2021,7.0,"Jason Reitman","Egon Spengler'ın torunları, onun mirasıyla Oklahoma'da hayaletlere karşı savaşır."],
["Ghostbusters: Frozen Empire",2024,5.9,"Gil Kenan","Spengler ailesi New York'a döner ve şehri donduracak kadim bir varlıkla yüzleşir."],
["Zombieland: Double Tap",2019,6.6,"Ruben Fleischer","Dört hayatta kalan, on yıl sonra yeni zombi türleriyle ve yeni sorunlarla karşılaşır."]],
yaratik:[
["Alien 3",1992,6.4,"David Fincher","Ripley, bir hapishane gezegenine düşerken yanında bir ksenomorf de gelmiştir."],
["Alien Resurrection",1997,6.2,"Jean-Pierre Jeunet","Ripley'in klonu, bilim insanlarının ksenomorf deneyleri sırasında uyandırılır."],
["Alien vs. Predator",2004,5.6,"Paul W.S. Anderson","Antarktika'daki bir piramitte Alien ve Predator karşı karşıya gelir, insanlar ortada kalır."],
["Aliens vs. Predator: Requiem",2007,4.7,"Colin Strause, Greg Strause","Melez yaratık, küçük bir Colorado kasabasında yayılır."],
["Alien: Covenant",2017,6.4,"Ridley Scott","Bir koloni gemisi, bilinmeyen bir gezegende ksenomorfla ve David'le karşılaşır."],
["Predator 2",1990,6.3,"Stephen Hopkins","Los Angeles'ta uyuşturucu çeteleriyle savaşan bir polis, Predator ile yüzleşir."],
["Predators",2010,6.4,"Nimród Antal","Birbirini tanımayan savaşçılar, yabancı bir gezegende bir Predator avının hedefi olur."],
["The Predator",2018,5.3,"Shane Black","Yere düşen bir Predator, bir grup eski askerin ve bir çocuğun yardımıyla yenilmeye çalışılır."],
["Prey",2022,7.1,"Dan Trachtenberg","1719'da genç bir Comanche savaşçısı, kabilesini tehdit eden Predator ile avlanır."],
["Jaws 2",1978,5.7,"Jeannot Szwarc","Amity'de yeni bir büyük beyaz köpekbalığı ortaya çıkar ve Brody yine uyarıda bulunur."],
["Jaws 3-D",1983,3.7,"Joe Alves","Bir deniz parkında köpekbalığı bu kez turistleri tehdit eder."],
["Jaws: The Revenge",1987,2.9,"Joseph Sargent","Brody ailesi, köpekbalığının intikam için peşlerinde olduğunu fark eder."],
["A Quiet Place Part II",2020,7.2,"John Krasinski","Abbott ailesi, sessizlik içinde yeni bir yer arayarak canavarlara karşı hayatta kalmaya çalışır."],
["A Quiet Place: Day One",2024,6.6,"Michael Sarnoski","İstilanın ilk günü New York'ta bir kadın ve kedisi, sessizce hayatta kalmaya çalışır."],
["The Descent: Part 2",2009,5.0,"Jon Harris","Hayatta kalan Sarah, kayıp arkadaşlarını bulmak için mağaraya yeniden döner."],
["Revenge of the Creature",1955,5.6,"Jack Arnold","Black Lagoon yaratığı yakalanır ve Florida'da bir akvaryuma getirilir."],
["The Creature Walks Among Us",1956,5.5,"John Sherwood","Bilim insanları yaratığı değiştirmeye çalışırken sonuç beklenmedik olur."]],
asya:[
["Ringu 2",1999,6.0,"Hideo Nakata","Sadako'nun laneti, ilk olaydan sonra hayatta kalanları ve gazetecileri takip eder."],
["Rasen",1998,5.8,"Jôji Iida","Ringu ile aynı romandan uyarlanan, lanetin bilimsel yönüne odaklanan bir film."],
["Ring 0: Birthday",2000,6.0,"Norio Tsuruta","Sadako'nun gençliği ve lanetinin kökeni anlatılan ön hikâye."],
["The Ring",2002,7.1,"Gore Verbinski","Ringu'nun Amerikan versiyonu: gazeteci Rachel, lanetli videoyu izleyenlerin yedi gün içinde öldüğünü fark eder."],
["The Ring Two",2005,5.4,"Hideo Nakata","Rachel ve oğlu, Samara'nın peşini bırakmayan ruhuyla yeniden karşılaşır."],
["Rings",2017,4.5,"F. Javier Gutiérrez","Bir üniversite öğrencisi, lanetli videonun yeni bir sürümünü keşfeder."],
["Sadako vs. Kayako",2016,5.2,"Kōji Shiraishi","Ringu'nun Sadako'su ile Ju-On'un Kayako'su aynı gençleri hedef alır."],
["Ju-on: The Grudge 2",2003,6.1,"Takashi Shimizu","Kayako'nun laneti, aynı eve giren yeni kişilere yayılmaya devam eder."],
["The Grudge",2004,5.9,"Takashi Shimizu","Japonya'da bir eve taşınan Amerikalı bakıcı, evdeki lanetin kurbanı olur."],
["The Grudge 2",2006,4.7,"Takashi Shimizu","Lanet Tokyo'dan Amerika'ya yayılır."],
["The Grudge",2020,4.1,"Nicolas Pesce","Polis dedektifi, birkaç ayrı ölüme neden olan lanetli evi araştırır."],
["Pulse",2006,4.7,"Jim Sonzero","Kairo'nun Amerikan versiyonu: internet üzerinden gelen hayaletler insanları yok eder."],
["Dark Water",2005,5.6,"Walter Salles","Japon filminin Amerikan yeniden çevrimi: boşanmakta olan anne ve kızı, sızıntılı bir apartman dairesinde ürkütücü şeylerle karşılaşır."],
["The Uninvited",2009,6.3,"Thomas Guard, Charles Guard","A Tale of Two Sisters'ın Amerikan versiyonu: hastaneden dönen genç kız, üvey annesinden şüphelenir."],
["Shutter",2008,5.2,"Masayuki Ochiai","Fotoğraflarda beliren hayaletle karşılaşan genç bir çiftin hikâyesi, Tayland filminin Amerikan versiyonu."],
["The Eye 2",2004,5.2,"Oxide Pang, Danny Pang","İntihar girişiminden sonra bir kadın, ölüm sonrası görüntüler görmeye başlar."],
["The Eye",2008,5.4,"David Moreau, Xavier Palud","Kornea nakli sonrası gözleri değişen bir kadın, ölülerin hayaletlerini görmeye başlar."]],
kozmik:[
["Cube 2: Hypercube",2002,5.0,"Andrzej Sekula","Sekiz kişi, bu kez dört boyutlu tuzaklarla dolu bir küp labirentte uyanır."],
["Cube Zero",2004,5.7,"Ernie Barbarash","Küp'ün nasıl yönetildiğini gösteren, tuzakları izleyen teknisyenlerin gözünden bir ön hikâye."]],
survival:[
["The Strangers: Prey at Night",2018,5.2,"Johannes Roberts","Bir aile, ıssız karavan parkında maskeli üç katilin hedefi olur."],
["The Strangers: Chapter 1",2024,4.9,"Renny Harlin","Bir çift, yolculuk sırasında bir kasabada maskeli saldırganlarla karşılaşır. Yeniden başlatılan bir üçlemenin ilk filmi."],
["Funny Games",2007,6.5,"Michael Haneke","Haneke'nin kendi 1997 filmini Amerika'da çektiği yeniden çevrimi."],
["Don't Breathe 2",2021,5.7,"Rodo Sayagues","Kör savaş gazisi, bu kez kızını kurtarmaya çalışırken yeni bir tehditle yüzleşir."],
["Wolf Creek 2",2013,6.1,"Greg McLean","Bir turist çifti, Avustralya çölünde Mick Taylor'ın yeni kurbanları olur."],
["The Hitcher",2007,5.6,"Dave Meyers","1986 filminin yeniden çevrimi: bir genç çift, otostopçu bir katile yol verir."],
["The Platform 2",2024,5.3,"Galder Gaztelu-Urrutia","Dikey hapishane, ilk filmin öncesinde farklı bir kurallı dünyada anlatılır."],
["Speak No Evil",2024,6.1,"James Watkins","Amerikalı bir aile, tatilde tanıştıkları İngiliz ailenin evinde hafta sonu geçirir. Danimarka filminin yeniden çevrimi."],
["Bird Box Barcelona",2023,5.1,"David Pastor, Álex Pastor","Barselona'da bir adam ve kızı, görünmeyen tehdide karşı hayatta kalmaya çalışır."]],
gotik:[
["Son of Frankenstein",1939,7.1,"Rowland V. Lee","Frankenstein'ın oğlu, babasının kalesine döner ve Igor ile yaratığı yeniden uyandırır."],
["The Ghost of Frankenstein",1942,6.2,"Erle C. Kenton","Yaratık, Frankenstein'ın ikinci oğlunun yardımıyla yeniden hayata döner."],
["Frankenstein Meets the Wolf Man",1943,6.4,"Roy William Neill","Kurt Adam, kendi ölümüne çare ararken Frankenstein'ın yaratığıyla karşılaşır."],
["House of Frankenstein",1944,6.2,"Erle C. Kenton","Dracula, Kurt Adam ve Frankenstein'ın yaratığı tek bir filmde bir araya gelir."],
["House of Dracula",1945,6.1,"Erle C. Kenton","Bir doktor, Dracula ve Kurt Adam'ı iyileştirmeye çalışırken ilişki karmaşıklaşır."],
["Dracula's Daughter",1936,6.4,"Lambert Hillyer","Dracula'nın kızı, babasının laneti altında kendini özgür kılmaya çalışır."],
["Son of Dracula",1943,6.3,"Robert Siodmak","Amerika'nın güneyinde Kont Alucard adındaki vampir, bir kadınla evlenmek ister."],
["The Invisible Man Returns",1940,6.6,"Joe May","Görünmez olan bir adam, haksız yere ölüm cezasına çarptırılırken gerçek katili aramaya çalışır."],
["The Invisible Man",2020,7.1,"Leigh Whannell","Şiddet içeren eski sevgilisinden kaçan bir kadın, onun intiharından sonra görünmez bir varlık tarafından takip edildiğini anlar."],
["The Mummy's Hand",1940,6.1,"Christy Cabanne","Arkeologlar, bir Mısır tapınağında Kharis adlı mumyayı uyandırır."],
["The Mummy's Tomb",1942,5.7,"Harold Young","Kharis, Amerika'ya gelerek eski mumya avcılarının ailesini hedef alır."],
["The Wolf Man",2010,5.8,"Joe Johnston","1941 filminin yeniden çevrimi: bir adam, ölen kardeşinin ardından köyüne döner ve kurt adam tarafından ısırılır."]]
};
window.EXTRA=window.EXTRA||{};
Object.keys(S).forEach(g=>{window.EXTRA[g]=(window.EXTRA[g]||[]).concat(S[g])});
})();
